version: '3.8'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devices
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@database:5432/devices
